# go-nexus 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8081
  mode: "release" # debug, release, test
  read_timeout: "30s"
  write_timeout: "30s"
  max_header_bytes: 1048576

# 数据库配置
database:
  type: "sqlite" # sqlite, postgresql
  dsn: "resource/data/go-nexus.db"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: "5m"

# 存储配置
storage:
  type: "filesystem" # filesystem, s3
  base_path: "/var/lib/go-nexus"

  # S3配置（当type为s3时使用）
  s3:
    endpoint: ""
    region: "us-east-1"
    bucket: "go-nexus-artifacts"
    access_key_id: ""
    secret_access_key: ""
    use_ssl: true

# 缓存配置
cache:
  type: "memory" # memory, redis
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    pool_size: 10

# 日志配置
log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "resource/log/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days

# 安全配置
security:
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expire: "24h"
  enable_https: false
  cert_file: ""
  key_file: ""

# 插件配置
plugins:
  enabled: ["maven", "npm"]
  path: "resource/plugins"
  configs:
    maven:
      checksum_policy: "strict" # strict, warn, ignore
      metadata_update_policy: "daily" # always, daily, never
    npm:
      registry_url: "https://registry.npmjs.org"
